### ISSUE TITLE
Rewrite frontend using React

### ISSUE THREAD

**Issue by ZucchiniZe** [sagemathinc/smc-public#8]
Is there any ongoing task of cleaning up the code? If so once it is done I could help spruce up the UI and move to a JS framework (Ember or React).

**Comment by williamstein** [comment]
Cool. We are currently evaluating moving to React.  It would be very
helpful if you could just think about how moving to react might work and
post your thoughts.  Thanks!!

On Thursday, May 28, 2015, Alex B notifications@github.com wrote:

> Is there any ongoing task of cleaning up the code? If so once it is done I
> could help spruce up the UI and move to a JS framework (Ember or React).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sagemathinc/smc-public/issues/8.

## 

Sent from my massive iPhone 6 plus.

**Comment by williamstein** [comment]
I've been looking into React further, and I'm 99% certain that I want to move SMC to use React.  I want to do it in a way that is extremely clear and readable and **consistent** even if multiple people work on the codebase.   I'll work on coming up with a style guide soon for this, e.g., some example code so that components have what I think is a nice clean look (using CJSX -- the coffeescript version of JSX), e.g., like in this picture:

![screen shot 2015-05-29 at 5 06 14 pm](https://cloud.githubusercontent.com/assets/1276278/7894749/136e3334-0625-11e5-9ab5-18ed568891ca.png)

**Comment by ZucchiniZe** [comment]
Is there any reason that we have to use CJSX? If not have you checked out the new ES6 syntax (e.g. https://github.com/ZucchiniZe/flux-people/blob/master/scripts/components/PeopleCreate.js)

**Comment by haraldschilly** [comment]
@ZucchiniZe personally, I hate any curly brackets style and coffeescript has also many small benefits that make the code quicker to read. (i.e.  the time I need to understand what is what). I also think there is no inherent need, because it can be mixed. Said that, I'm in favor that william's style guide narrows down such dualities to avoid having to switch around in your head.

Regarding @williamstein's example, I like that it starts with a definition of the property types. This is in my eyes immense helpful, because you have to read a few lines and then you know what the underlying persistent data structure is. What's missing (in general) would be the [stateful data structures](https://facebook.github.io/react/docs/component-specs.html#getinitialstate) ... right? But first we have to learn a bit more about React ;-)

**Comment by ZucchiniZe** [comment]
What are we going to use to move around the data? The facebook implmentation of flux or [alt](github.com/goatslacker/alt) because I have experience using alt for moving data around.

**Comment by williamstein** [comment]
Probably alt since Facebook flux seems pretty bare bones.

On Saturday, May 30, 2015, Alex B notifications@github.com wrote:

> What are we going to use to move around the data? The facebook
> implmentation of flux or alt http://github.com/goatslacker/alt because
> I have experience using alt for moving data around.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sagemathinc/smc-public/issues/8#issuecomment-107092559
> .

## 

Sent from my massive iPhone 6 plus.

**Comment by ZucchiniZe** [comment]
Ok, how are we going to manage all the files so anyone can start collaborating?

**Comment by williamstein** [comment]
We should start by making a large list of all he components of SMC (not in
the technical sense of react components).   E.g., file upload, task list,
terminal, code mirror editor, jupyter notebook, project list, account
settings, ...

On Saturday, May 30, 2015, Alex B notifications@github.com wrote:

> Ok, how are we going to manage all the files so anyone can start
> collaborating?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sagemathinc/smc-public/issues/8#issuecomment-107093919
> .

## 

Sent from my massive iPhone 6 plus.

**Comment by williamstein** [comment]
I'll make a template and convert some things first, and ensure I like how things are working.  One of the GSoC projects is also to make it easier (=possible) for other people to work on the codebase.  

I've been looking at different flux implementations today, especially using them from coffeescript and worrying about simplicity.  So far, I think I like flummox the best.

**Comment by williamstein** [comment]
I've rewritten the account settings page using react (and cjsx), and it's now live.   This should provide a template to get things going.  

Next I need to come up with a script that creates dedicated virtual machines for developers to use to work (with the possibility of easy online collaboration) on the react rewrite.  I hope to do this by tomorrow.

**Comment by williamstein** [comment]
The new react code is in flux.coffee, and in the files `r_*.cjsx` here: https://github.com/sagemathinc/smc-public/tree/master/page

**Comment by williamstein** [comment]
Moved to https://github.com/sagemathinc/smc/issues/3
